### ISSUE TITLE
recurring resources

### ISSUE THREAD

**Issue by MaGerbig** [redhat-cop/patch-operator#11]
Hi, I'm currently using something like:

values.yaml:
machineZones:
  - zone: ap-southeast-1a
  - zone: ap-southeast-1b
  - zone: ap-southeast-1c
...

template.yaml:
{{ range $machineset := .Values.machineZones }}
---
apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: {{ $.Values.cluster.name }}-{{ $.Values.cluster.worker }}-{{ $machineset.zone }}
  namespace: "openshift-machine-api"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  minReplicas: {{ $.Values.machineAutoscaler.minReplicas }}
  maxReplicas: {{ $.Values.machineAutoscaler.maxReplicas }}
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ $.Values.cluster.name }}-{{ $.Values.cluster.worker }}-{{ $machineset.zone }}
{{ end }}

Asuming the 3 MachineSets already exist, any way to read the zones and fill in with the patch-operator ?

**Comment by raffaelespazzoli** [comment]
`any way to read the zones` not sure what you mean here, but if you mean to read the zone of an installed machineset, you can use the lookup function: https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-lookup-function
`and fill in with the patch-operator` the lookup function can be used in a patch template in the patch operator. I am still not clear on what you are trying to do.

**Comment by raffaelespazzoli** [comment]
may I close this?
