### ISSUE TITLE
Difference between resource-locker and this?

### ISSUE THREAD

**Issue by nwmcsween** [redhat-cop/patch-operator#2]
Both seem to have the same functionality with resource-locker being a superset of patch-operator? If so a possible reasoning for this over resource-locker

**Comment by raffaelespazzoli** [comment]
yes, thanks for the question, this explanation is overdue. The resource locker operator name was confusing and people, by and large, were only using the patch feature.
So I decided to change the name and add a couple of features:
1. you can not patch multiple objects with a single patch definition. So for example you can say patch all the service accounts with the label so and so.
2. if you don't need continuous enforcing of the patch, you can just patch objects at creation time with a mutating webhook.
My intention is to deprecate the resource locker operator soon (after I have some confirmation that the patch operator is stable).

**Comment by raffaelespazzoli** [comment]
may I close this?

**Comment by nwmcsween** [comment]
Sure
