### ISSUE TITLE
OLM-installed controller-manager get OOMKilled

### ISSUE THREAD

**Issue by larsks** [redhat-cop/patch-operator#48]
The patch operator controller-manager pod is get OOMKilled due to memory usage. 

On the node, we see:

> Sep 20 15:54:40 ctl-1 kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=crio-370504c90f749d6c5b1a4dc36ee9404d2467c669e01a56f30ac77c1f238c313a.scope,mems_allowed=0-1,oom_memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod966588f9_b8c8_4eda_a907_dd30fe21972e.slice/crio-370504c90f749d6c5b1a4dc36ee9404d2467c669e01a56f30ac77c1f238c313a.scope,task_memcg=/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod966588f9_b8c8_4eda_a907_dd30fe21972e.slice/crio-370504c90f749d6c5b1a4dc36ee9404d2467c669e01a56f30ac77c1f238c313a.scope,task=manager,pid=2231452,uid=1000760000
>
> Sep 20 15:54:40 ctl-1 kernel: Memory cgroup out of memory: Killed process 2231452 (manager) total-vm:8090736kB, anon-rss:500676kB, file-rss:25904kB, shmem-rss:0kB, UID:1000760000 pgtables:1976kB oom_score_adj:999

This is when trying to apply a single, minimal patch; you can see the complete test in https://github.com/larsks/patch-operator-test. This seems like a bug; nothing we're doing here should result in substantial memory consumption.

If we wanted to try increasing the resource limits for the pod, is there a way to influence the `resources` section of the deployment? Or is our only alternative to deploy without using OLM and edit the manifests directly? Is there anything we can do to help figure out why we're hitting memory limits?

**Comment by raffaelespazzoli** [comment]
please see this: https://github.com/redhat-cop/patch-operator#patch-controller-performance-considerations
and this: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md#resources

**Comment by larsks** [comment]
Thanks. I had already seen the [first document](https://github.com/redhat-cop/patch-operator#patch-controller-performance-considerations), but we only have a single patch defined on the entire cluster (and the cluster isn't even hosting user workloads yet, so the number of total secrets isn't huge [approx 2300 right now]). I'm surprised we're hitting limits in that situation.

I'm following the second document to increase the resource allocation for the controller pod.

**Comment by larsks** [comment]
Increasing the resource quota appears to have addressed the problem.
