### ISSUE TITLE
Change failurePolicy to Ignore

### ISSUE THREAD

**Issue by RobMokkink** [redhat-cop/patch-operator#49]
Please adjust the example code for the mutatingwebhook, so that it may fail when the patch-operator service is not reachable.
Change the ```failurePolicy``` to:

```failurePolicy: Ignore```

Otherwise it will cause issues when doing maintenance and the mutatingwebhook is blocking the creation of secrets and or configmaps, when the patch-operator service is not reachable.

**Comment by raffaelespazzoli** [comment]
so you'd be willing to lose events and let things be created/updated without the patch being applied? I'm not sure what you are proposing is the right direction. Perhaps it would be best to invest in an HA deployment of the operator to minimized the un-availability time.

**Comment by RobMokkink** [comment]
> so you'd be willing to lose events and let things be created/updated without the patch being applied? I'm not sure what you are proposing is the right direction. Perhaps it would be best to invest in an HA deployment of the operator to minimized the un-availability time.

If the service is HA we will not run into these issues. At the moment it is not safe to do maintenance if the service is not HA.

**Comment by raffaelespazzoli** [comment]
@RobMokkink you are in control of it. You can scale the operator deployment to how many replicas you want.
