### ISSUE TITLE
Installation via helm fails due to unmounted volumes

### ISSUE THREAD

**Issue by rasheedamir** [redhat-cop/patch-operator#74]
`Unable to attach or mount volumes: unmounted volumes=[patch-operator-certs webhook-server-cert], unattached volumes=[patch-operator-certs kube-api-access-wdqqk webhook-server-cert]: timed out waiting for the condition`

**Comment by trevorbox** [comment]
Is this deployed onto OpenShift or Kubernetes? The helm chart supports the --set enableCertManager=true flag if deploying into k8s to use cert manager to create the certificates. 
On OpenShift, the serving certificate is created automatically from the service.alpha.openshift.io/serving-cert-secret-name annotation in the Services.

**Comment by rasheedamir** [comment]
Thanks @trevorbox! it worked
