### ISSUE TITLE
controller manager pod stuck at CrashLoopBackOff 

### ISSUE THREAD

**Issue by Meza1923** [redhat-cop/patch-operator#8]
Hey,

I'm trying to use patch operator, and the pod got into CrashLoopBackOff state.

I found this in the logs:
"panic: runtime error: invalid memory address or nil pointer dereference" 

There is anything to do? 

Beside, I have to say that this tool is absolutely great

**Comment by raffaelespazzoli** [comment]
can you attach you patch CR and the full stack of the panic error?

**Comment by Meza1923** [comment]
> 

I'm working on it, but right now I can not.

Beside to my problem, the MutaingWebhookConfiguration object has interferes to my helm install tries.
The error was: "Hook pre-install .... failed: internal error occurred: failed calling webhook "patch-operator-inject.redhatocp.redhat.io" Post "https://patch-operator-webhook-service.patch-operator.svc:443/inject?timeout=10s: service "patch-operator-webhook-service" not found 
  
Thank you for your answer.

**Comment by raffaelespazzoli** [comment]
may I close this?

**Comment by Meza1923** [comment]
@raffaelespazzoli 
I guess this it the only option, thanks.
